services:
  # WGDashboard service https://github.com/jinndi/WGDashboard
  wgd:
    image: ghcr.io/jinndi/wgdashboard:latest
    container_name: wgd
    restart: unless-stopped
    environment:
      TZ: "Europe/Amsterdam"
      HOST: ""
      PORT: "10086"
      ALLOW_FORWARD: ""
    volumes:
      - wgd_data:/data
      - wgd_wgconf:/etc/wireguard
      - wgd_awgconf:/etc/amnezia/amneziawg
      - /lib/modules:/lib/modules:ro
    network_mode: "service:sb"
    cap_add:
      - NET_ADMIN

  # sing-box service https://github.com/jinndi/sing-box
  sb:
    image: ghcr.io/jinndi/sing-box:latest
    container_name: sb
    restart: unless-stopped
    environment:
      TZ: "Europe/Amsterdam"
      LOG_LEVEL: "fatal"
      DNS_DIRECT: "https://dns.google"
      DNS_PROXY: "tls://one.one.one.one"
      DNS_PROXY_TTL: "300"
      ENABLE_ADGUARD: "false"
      BLOCK_GEOSITE: ""
      BLOCK_GEOIP: ""
      BLOCK_SITES: ""
      PROXY_LINK: ""
      WARP_OVER_PROXY: "false"
      WARP_OVER_DIRECT: "false"
      ROUTE_CIDR: ""
      ROUTE_FINAL: "direct"
      BYPASS_GEOSITE: ""
      BYPASS_GEOIP: ""
      PASS_SITES: ""
      BITTORRENT: "direct"
    ports:
      # wgd service ports:
      - 10086:10086/tcp
      - 51820-51830:51820-51830/udp
      # caddy service ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    volumes:
      - sb_data:/data
      - /lib/modules:/lib/modules:ro
      # ! Add your custom hosts file here if you want to use it
      #- ./hosts:/opt/hosts:ro
    networks:
      - sb_net
    privileged: true

  # caddy service https://github.com/jinndi/caddy
  # ! Remove this service if you could not get a domain for the panel
  caddy:
    image: ghcr.io/jinndi/caddy:latest
    restart: unless-stopped
    container_name: caddy
    environment:
      TZ: "Europe/Amsterdam"
      DOMAIN: ""
      EMAIL: ""
      PROXY: ""
      PROXY_STRIP_PREFIX: "wgd:10086/dashboard"
      LOG_LEVEL: "info"
    volumes:
      - caddy_data:/data
      - caddy_conf:/config
    network_mode: "service:sb"
    cap_add:
      - NET_ADMIN

volumes:
  wgd_data:
    name: wgd_data
    driver: local
  wgd_wgconf:
    name: wgd_wgconf
    driver: local
  wgd_awgconf:
    name: wgd_awgconf
    driver: local
  sb_data:
    name: sb_data
    driver: local
  # ! Remove this volumes if you could not get a domain for the panel
  caddy_data:
    name: caddy_data
    driver: local
  caddy_conf:
    name: caddy_conf
    driver: local

networks:
  sb_net:
    name: sb_net
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.100.0/24
        - subnet: fd00:dead:beef:100::/64
