services:
  wgd:
    image: ghcr.io/jinndi/wgdashboard:latest
    container_name: wgd
    restart: unless-stopped
    # All environments optional.
    # Description: https://github.com/jinndi/WGDashboard-sing-box?tab=readme-ov-file#environment-variables-of-the-wgd-service
    environment:
      TZ: "Europe/Amsterdam"
      WGD_HOST: ""
      WGD_PORT: "10086"
      LOG_LEVEL: "fatal"
      DNS_DIRECT: "https://dns.google"
      DNS_PROXY: "tls://one.one.one.one"
      DNS_PROXY_TTL: "300"
      ALLOW_FORWARD: ""
      ENABLE_ADGUARD: "false"
      BLOCK_GEOSITE: ""
      BLOCK_GEOIP: ""
      BLOCK_SITES: ""
      PROXY_LINK: ""
      WARP_OVER_PROXY: "false"
      WARP_OVER_DIRECT: "false"
      ROUTE_CIDR: ""
      ROUTE_FINAL: "direct"
      BYPASS_GEOSITE: ""
      BYPASS_GEOIP: ""
      PASS_SITES: ""
      BITTORRENT: "direct"
    ports:
      - 10086:10086/tcp
      - 51820-51830:51820-51830/udp
    volumes:
      - wgd_data:/data
      - wgd_wgconf:/etc/wireguard
      - wgd_awgconf:/etc/amnezia/amneziawg
      - /lib/modules:/lib/modules:ro
      # ! Add your custom hosts file here if you want to use it
      #- ./hosts:/opt/hosts:ro
    networks:
      - wgd_net
    privileged: true

  # ! Remove this service if you could not get a domain for the panel
  # Description: https://github.com/jinndi/WGDashboard-sing-box?tab=readme-ov-file#environment-variables-of-the-wgd-service
  wgd-caddy:
    image: ghcr.io/jinndi/caddy:latest
    restart: unless-stopped
    container_name: wgd-caddy
    environment:
      DOMAIN: ""
      EMAIL: ""
      PROXY: ""
      PROXY_STRIP_PREFIX: "wgd:10086/dashboard"
      LOG_LEVEL: "info"
    ports:
      - 443:443/tcp
      - 443:443/udp
    volumes:
      - wgd_caddydata:/data
      - wgd_caddyconf:/config
    networks:
      - wgd_net
    cap_add:
      - NET_ADMIN

volumes:
  wgd_data:
    name: wgd_data
    driver: local
  wgd_wgconf:
    name: wgd_wgconf
    driver: local
  wgd_awgconf:
    name: wgd_awgconf
    driver: local
  # ! Remove this volumes if you could not get a domain for the panel
  wgd_caddydata:
    name: wgd_caddydata
    driver: local
  wgd_caddyconf:
    name: wgd_caddyconf
    driver: local

networks:
  wgd_net:
    name: wgd_net
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.100.0/24
        - subnet: fd00:dead:beef:100::/64
